---
- name: list files
  hosts: ansi-child
  remote_user: openhabian
  vars:
    prompt_text: "what is the file name you want to create?"
    
  vars_prompt:
  - name: filename 
    prompt: "{{ prompt_text }}"
    private: no # yes for password 

  tasks:
  - name: print whoami
    shell: whoami
  - name: list files 
    find:
      paths: /tmp
      recurse: yes
  - name: create file 
    file: 
      path: ~/{{ filename}}
      owner: openhabian
      group: openhabian
      state: touch
      mode: '0755'
  - name: Check is ls installed
    shell: command -v lks >/dev/null 2>&1
    register: is_ls_exist
    ignore_errors: yes

  - debug: msg="{{ is_ls_exist.rc }}" # it returns rc 0
  - debug: var=is_ls_exist